---
abstract: 'Install the Tags modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Tags
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Tags: 0.06
  Tags::Element: 0.02
  Tags::Output::Indent: 0.05
  Tags::Output::LibXML: 0.02
  Tags::Output::PYX: 0.03
  Tags::Output::Structure: 0.04
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Tags
  homepage: https://github.com/tupinek/Task-Tags
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-Tags
version: '0.06'
